version: "2.0"
services:
  db:
    image: mysql:5.7
    container_name: "db-${APPLICATION_NAME}"
    expose: 
      - 3306
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}  

  backend:
    build: ./back-end
    image: "api-${APPLICATION_NAME}"
    container_name: "api-${APPLICATION_NAME}"
    expose: 
      - 19000
    ports: 
      - "19000:19000"
    environment: 
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on: 
      - db

  frontend:
    build: 
      context: ./front-end
      args: 
        VUE_APP_API_URL: ${VUE_APP_API_URL}
    image: "front-${APPLICATION_NAME}"
    container_name: "front-${APPLICATION_NAME}"    
    expose: 
      - 80
    ports: 
      - "9000:80"
    depends_on: 
      - db
      - backend