// <auto-generated />
using System;
using DotnetCoreCrud.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotnetCoreCrud.Data.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20200713174036_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DotnetCoreCrud.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("varchar(128)");

                    b.HasKey("Guid");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("DotnetCoreCrud.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("guid")
                        .HasColumnType("char(36)");

                    b.Property<float>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("float(6,3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("UnitValue")
                        .HasColumnName("unit_value")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Unity")
                        .IsRequired()
                        .HasColumnName("unity")
                        .HasColumnType("char(3)");

                    b.Property<Guid?>("product_category")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.HasKey("Guid");

                    b.HasIndex("product_category");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("DotnetCoreCrud.Domain.Entities.Product", b =>
                {
                    b.HasOne("DotnetCoreCrud.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("product_category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
