version: "2.0"
services:
  db:
    image: mysql:5.7
    container_name: "db-${APPLICATION_NAME}"
    expose: 
      - 3306
    ports:
      - "3306:3306"
    env_file: 
      - ./.env
    environment: 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  
  backend:
    build: .
    image: "api-${APPLICATION_NAME}"
    container_name: "api-${APPLICATION_NAME}"
    expose: 
      - 19000
    ports: 
      - "19000:19000"
    depends_on: 
      - db